%% Setup
add_paths
C.stroke = 10;
C.piston_min_length = 11;
C.pressure = 1;
m = 3.5;%factor for compression vs extension stroke sizes

%% Four double acting with 4 levels of power
pistons =  [
            [false;0;m] [true;0;1]...
            [false;90;m] [true;90;1]...
            [false;180;m] [true;180;1]...
            [false;270;m] [true;270;1]...
            ];


on_off_matrix = [1 1 1 1 1 1 1 1;...
                 1 0 1 0 1 0 1 0;...
                 0 1 0 1 0 1 0 1;...
                 1 0 0 1 1 0 0 1;...
                 ];

plot_combinations(C,pistons,on_off_matrix);
%% Four double acting with all possible levels of power
pistons =  [
            [false;0;m] [true;0;1]...
            [false;90;m] [true;90;1]...
            [false;180;m] [true;180;1]...
            [false;270;m] [true;270;1]...
            ];

plot_combinations(C,pistons);
%% 3 single acting with all possible levels of power
pistons =  [
            [false;0;1]...
            [false;90;1]...
            [false;180;1]...
            [false;270;1]...
            ];

plot_combinations(C,pistons,0,[1 2 3 4 5 6]);